[workspace]
members = [
  "jupiter-swap-api-client",
  "example",
]

[workspace.package]
edition = "2021"

[workspace.dependencies]
solana-account-decoder = "2.0.13"
solana-client = "2.0.13"
solana-sdk = "2.0.13"
